/**
 * ESC/POS command fixtures.
 *
 * Command sequences only. Arabic byte expectations live in
 * cp864-conformance.test.ts and are taken from the published code-page
 * mappings, never generated by the codec under test — that conflation is what
 * let revision 3 ship an invented CP864 table with a green suite.
 */

export const ESC_INIT = [0x1b, 0x40];
export const ESC_SELECT_CP1256 = [0x1b, 0x74, 0x16];
export const ESC_SELECT_CP864 = [0x1b, 0x74, 0x25];
export const ESC_ALIGN_CENTER = [0x1b, 0x61, 0x01];
export const GS_PARTIAL_CUT = [0x1d, 0x56, 0x01];
export const GS_FULL_CUT = [0x1d, 0x56, 0x00];

/** `GS ( k` model-2 selection — the first command of any native QR. */
export const QR_MODEL_2 = [0x1d, 0x28, 0x6b, 0x04, 0x00, 0x31, 0x41, 0x32, 0x00];

/** `GS ( k` print — the last command of any native QR. */
export const QR_PRINT = [0x1d, 0x28, 0x6b, 0x03, 0x00, 0x31, 0x51, 0x30];

/** `GS v 0` — raster bit image header. */
export const GS_RASTER = [0x1d, 0x76, 0x30, 0x00];
