import { describe, expect, it } from 'vitest';
import { encodeCodePage, canEncode } from '../encoding/codepage.js';
import { shapeArabic } from '../encoding/arabic-shaping.js';
import { UnsupportedCharacterError } from '../errors.js';

/**
 * PC864 conformance, against the standard rather than against ourselves.
 *
 * Every expectation here is taken from the authoritative Microsoft/Unicode
 * PC864 mapping (CP864.TXT), which Epson documents as character code table 37.
 * None is generated by the codec under test.
 *
 * That distinction is the whole reason this file exists. Revision 3 shipped an
 * invented CP864 table and then produced its golden fixtures *from* that table,
 * so the fixtures and the bug agreed with each other and the suite was green.
 * A fixture derived from the implementation cannot detect the implementation
 * being wrong.
 */

/** Verbatim from the authoritative mapping. */
const AUTHORITATIVE: readonly (readonly [number, number, string])[] = [
  [0xfefb, 0x9d, 'LAM WITH ALEF ISOLATED'],
  [0xfefc, 0x9e, 'LAM WITH ALEF FINAL'],
  [0xfe8e, 0xa8, 'ALEF FINAL'],
  [0xfee3, 0xe5, 'MEEM INITIAL'],
  [0xfeed, 0xe8, 'WAW ISOLATED'],
  [0x066a, 0x25, 'ARABIC PERCENT SIGN'],
  [0xfe8d, 0xc7, 'ALEF ISOLATED'],
  [0xfea9, 0xcf, 'DAL ISOLATED'],
  [0xfead, 0xd1, 'REH ISOLATED'],
];

describe('authoritative PC864 mappings', () => {
  it.each(AUTHORITATIVE)('maps U+%s to 0x%s (%s)', (codePoint, byte) => {
    expect(Array.from(encodeCodePage(String.fromCodePoint(codePoint), 'cp864'))).toEqual([byte]);
  });

  it('does not map lam-alef onto WAW ISOLATED', () => {
    // Revision 3's specific defect: 0xE8 is WAW ISOLATED, and lam-alef was
    // mapped onto it. Two different letters sharing one byte.
    const lamAlef = Array.from(encodeCodePage('ﻻ', 'cp864'))[0];
    const waw = Array.from(encodeCodePage('ﻭ', 'cp864'))[0];
    expect(lamAlef).toBe(0x9d);
    expect(waw).toBe(0xe8);
    expect(lamAlef).not.toBe(waw);
  });

  it('keeps every byte assignment unique', () => {
    // A collision means two characters print identically — the symptom of an
    // invented table, which is how revision 3 put lam-alef on WAW's byte.
    const seen = new Map<number, number>();
    let stripped = 0;

    for (let codePoint = 0x80; codePoint <= 0xffff; codePoint += 1) {
      const character = String.fromCodePoint(codePoint);
      if (!canEncode(character, 'cp864')) continue;

      const bytes = Array.from(encodeCodePage(character, 'cp864'));
      if (bytes.length === 0) {
        // A combining mark: PC864 has no cell for harakat, so they are dropped
        // rather than substituted. Zero bytes is the correct outcome.
        stripped += 1;
        continue;
      }

      const byte = bytes[0] as number;
      const previous = seen.get(byte);
      expect(
        previous,
        `0x${byte.toString(16)} is claimed by both U+${(previous ?? 0).toString(16)} and ` +
          `U+${codePoint.toString(16)}`,
      ).toBeUndefined();
      seen.set(byte, codePoint);
    }

    expect(seen.size).toBeGreaterThan(100);
    expect(stripped).toBeGreaterThan(0);
  });
});

describe('unsupported forms are rejected, never substituted', () => {
  it('rejects presentation forms absent from PC864', () => {
    // PC864 carries only part of the Presentation Forms-B block. These are
    // genuinely absent, and a substitute glyph on a tax invoice is worse than
    // a refusal an operator can see.
    for (const codePoint of [0xfe70, 0xfe72, 0xfe76, 0xfe88, 0xfe90, 0xfe92]) {
      expect(() => encodeCodePage(String.fromCodePoint(codePoint), 'cp864')).toThrow(
        UnsupportedCharacterError,
      );
    }
  });

  it('rejects a fully shaped word PC864 cannot represent', () => {
    // مرحبا shapes to forms including MEEM INITIAL (present) and BEH MEDIAL
    // (absent), so the word as a whole is not encodable.
    expect(canEncode(shapeArabic('مرحبا'), 'cp864')).toBe(false);
    expect(() => encodeCodePage(shapeArabic('مرحبا'), 'cp864')).toThrow(UnsupportedCharacterError);
  });

  it('cannot carry the shaper output in general', () => {
    // The measurement behind ADR-0011: a large fraction of the forms the
    // shaper produces simply do not exist in PC864, which is why Arabic goes
    // to raster rather than through this code page.
    const words = ['مرحبا', 'متجر كورفي', 'ضريبة القيمة المضافة', 'ماء بارد', 'فاتورة'];
    const unencodable = words.filter((word) => !canEncode(shapeArabic(word), 'cp864'));
    expect(unencodable.length).toBeGreaterThan(0);
  });

  it('rejects non-Arabic characters outside the page', () => {
    expect(() => encodeCodePage('日本語', 'cp864')).toThrow(UnsupportedCharacterError);
  });

  it('still passes ASCII through unchanged', () => {
    expect(Array.from(encodeCodePage('INV-1', 'cp864'))).toEqual([0x49, 0x4e, 0x56, 0x2d, 0x31]);
  });
});

describe('CP1256 conformance', () => {
  /** Verbatim from the Windows-1256 mapping. */
  const WINDOWS_1256: readonly (readonly [number, number])[] = [
    [0x0627, 0xc7], // ALEF
    [0x0628, 0xc8], // BEH
    [0x0645, 0xe3], // MEEM
    [0x0648, 0xe6], // WAW
    [0x064a, 0xed], // YEH
    [0x0644, 0xe1], // LAM
  ];

  it.each(WINDOWS_1256)('maps U+%s to 0x%s', (codePoint, byte) => {
    expect(Array.from(encodeCodePage(String.fromCodePoint(codePoint), 'cp1256'))).toEqual([byte]);
  });

  it('carries base letters, not presentation forms', () => {
    // The complement of CP864: CP1256 holds the unshaped alphabet and expects
    // the firmware to join it.
    expect(canEncode('مرحبا', 'cp1256')).toBe(true);
    expect(canEncode('ﻻ', 'cp1256')).toBe(false);
  });
});
